version: '3.8'

services:
  scraper:
    build: .
    volumes:
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python app.py > /app/output/results.json" 