version: '3.8'

services:
  scraper:
    build: .
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "mkdir -p /app/logs && python app.py 2>&1 | tee /app/logs/job_scraper.log" 